
INSERT INTO CHAM.CHAM_MONIMAP_CARD_OWNER_POSITION( CHAM_MONIMAP_CARD_OWNER_POSITION_NAME, REGIST_DATE, MODIFY_DATE)
    VALUE ('국회의원',CURRENT_TIME,CURRENT_TIME);

INSERT INTO CHAM.CHAM_MONIMAP_CARD_OWNER_POSITION( CHAM_MONIMAP_CARD_OWNER_POSITION_NAME, REGIST_DATE, MODIFY_DATE)
    VALUE ('광역지자체장',CURRENT_TIME,CURRENT_TIME);

INSERT INTO CHAM.CHAM_MONIMAP_CARD_OWNER_POSITION( CHAM_MONIMAP_CARD_OWNER_POSITION_NAME, REGIST_DATE, MODIFY_DATE)
    VALUE ('광역의회',CURRENT_TIME,CURRENT_TIME);

INSERT INTO CHAM.CHAM_MONIMAP_CARD_OWNER_POSITION( CHAM_MONIMAP_CARD_OWNER_POSITION_NAME, REGIST_DATE, MODIFY_DATE)
    VALUE ('기지자체장',CURRENT_TIME,CURRENT_TIME);

INSERT INTO CHAM.CHAM_MONIMAP_CARD_OWNER_POSITION( CHAM_MONIMAP_CARD_OWNER_POSITION_NAME, REGIST_DATE, MODIFY_DATE)
    VALUE ('기초의회',CURRENT_TIME,CURRENT_TIME);

INSERT INTO CHAM.CHAM_MONIMAP_CARD_OWNER_POSITION( CHAM_MONIMAP_CARD_OWNER_POSITION_NAME, REGIST_DATE, MODIFY_DATE)
    VALUE ('기타',CURRENT_TIME,CURRENT_TIME);


INSERT INTO CHAM.CHAM_MONIMAP_ROLE (CHAM_MONIMAP_ROLE_NAME) VALUES ('ADMIN');
INSERT INTO CHAM.CHAM_MONIMAP_ROLE (CHAM_MONIMAP_ROLE_NAME) VALUES ('USER');
INSERT INTO CHAM.CHAM_MONIMAP_ROLE (CHAM_MONIMAP_ROLE_NAME) VALUES ('ANONYMOUS');



INSERT INTO CHAM.CHAM_MONIMAP_ROLE_HIERARCHY (CHAM_MONIMAP_ROLE_NAME, CHAM_MONIMAP_PARENT_ROLE_ID) VALUES ('ADMIN', null);
INSERT INTO CHAM.CHAM_MONIMAP_ROLE_HIERARCHY (CHAM_MONIMAP_ROLE_NAME, CHAM_MONIMAP_PARENT_ROLE_ID) VALUES ('USER', 1);
INSERT INTO CHAM.CHAM_MONIMAP_ROLE_HIERARCHY (CHAM_MONIMAP_ROLE_NAME, CHAM_MONIMAP_PARENT_ROLE_ID) VALUES ('ANONYMOUS', 2);

COMMIT;