
INSERT INTO CARD_OWNER_POSITION( CARD_OWNER_POSITION_NAME, REGIST_DATE, MODIFY_DATE)
    VALUE ('국회의원',CURRENT_TIME,CURRENT_TIME);

INSERT INTO CARD_OWNER_POSITION( CARD_OWNER_POSITION_NAME, REGIST_DATE, MODIFY_DATE)
    VALUE ('광역지자체장',CURRENT_TIME,CURRENT_TIME);

INSERT INTO CARD_OWNER_POSITION( CARD_OWNER_POSITION_NAME, REGIST_DATE, MODIFY_DATE)
    VALUE ('광역의회',CURRENT_TIME,CURRENT_TIME);

INSERT INTO CARD_OWNER_POSITION( CARD_OWNER_POSITION_NAME, REGIST_DATE, MODIFY_DATE)
    VALUE ('기지자체장',CURRENT_TIME,CURRENT_TIME);

INSERT INTO CARD_OWNER_POSITION( CARD_OWNER_POSITION_NAME, REGIST_DATE, MODIFY_DATE)
    VALUE ('기초의회',CURRENT_TIME,CURRENT_TIME);

INSERT INTO CARD_OWNER_POSITION( CARD_OWNER_POSITION_NAME, REGIST_DATE, MODIFY_DATE)
    VALUE ('기타',CURRENT_TIME,CURRENT_TIME);


COMMIT;