-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- CARD_OWNER_POSITION Table Create SQL
-- 테이블 생성 SQL - CHAM.CARD_OWNER_POSITION
CREATE TABLE CHAM.CARD_OWNER_POSITION
(
    `CARD_OWNER_POSITION_ID`    BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '카드 승인자 직위 ID',
    `CARD_OWNER_POSITION_NAME`  VARCHAR(100)    NULL        COMMENT '카드 승인자 직위 이름',
    `REGIST_DATE`               DATETIME        NULL        COMMENT '생성 일시',
    `MODIFY_DATE`               DATETIME        NULL        COMMENT '수정 일시',
    PRIMARY KEY (CARD_OWNER_POSITION_ID)
);

-- 테이블 Comment 설정 SQL - CHAM.CARD_OWNER_POSITION
ALTER TABLE CHAM.CARD_OWNER_POSITION COMMENT '카드_승인자_직위';


-- CARD_USE_ADDR Table Create SQL
-- 테이블 생성 SQL - CHAM.CARD_USE_ADDR
CREATE TABLE CHAM.CARD_USE_ADDR
(
    `CARD_USE_ADDR_ID`      BIGINT           NOT NULL    AUTO_INCREMENT COMMENT '카드 사용 장소 ID',
    `CARD_USE_ADDR_NAME`    VARCHAR(1000)    NULL        COMMENT '카드 사용 장소 이름',
    `CARD_USE_DETAIL_ADDR`  VARCHAR(4000)    NULL        COMMENT '카드 사용 상세 장소',
    `CARD_USE_IMAGE_URL`    VARCHAR(1000)    NULL        COMMENT '카드 사용 이미지 URL',
    `REGIST_DATE`           DATETIME         NULL        COMMENT '생성 일시',
    `MODIFY_DATE`           DATETIME         NULL        COMMENT '수정 일시',
    PRIMARY KEY (CARD_USE_ADDR_ID)
);

-- 테이블 Comment 설정 SQL - CHAM.CARD_USE_ADDR
ALTER TABLE CHAM.CARD_USE_ADDR COMMENT '카드_사용_장소';


-- MEMBER Table Create SQL
-- 테이블 생성 SQL - CHAM.MEMBER
CREATE TABLE CHAM.MEMBER
(
    `MEMBER_ID`           BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '회원 ID',
    `MEMBER_EMAIL`        VARCHAR(100)    NULL        COMMENT '회원 이메일',
    `MEMBER_NAME`         VARCHAR(100)    NULL        COMMENT '회원 이름',
    `MEMBER_SOCIAL_TYPE`  VARCHAR(50)     NULL        COMMENT '회원 소셜 타입',
    `REGIST_DATE`         DATETIME        NULL        COMMENT '생성 일시',
    `MODIFY_DATE`         DATETIME        NULL        COMMENT '수정 일시',
    PRIMARY KEY (MEMBER_ID)
);

-- 테이블 Comment 설정 SQL - CHAM.MEMBER
ALTER TABLE CHAM.MEMBER COMMENT '회원';


-- CARD_USE Table Create SQL
-- 테이블 생성 SQL - CHAM.CARD_USE
CREATE TABLE CHAM.CARD_USE
(
    `CARD_USE_ID`             BIGINT           NOT NULL    AUTO_INCREMENT COMMENT '카드 사용 ID',
    `CARD_OWNER_POSITION_ID`  BIGINT           NULL        COMMENT '카드 승인자 직위 ID',
    `CARD_USE_ADDR_ID`        BIGINT           NULL        COMMENT '카드 사용 장소 ID',
    `CARD_USE_NAME`           VARCHAR(100)     NULL        COMMENT '카드 사용 이름',
    `CARD_USE_DATE`           DATE             NULL        COMMENT '카드 사용 일시',
    `CARD_USE_TIME`           TIME             NULL        COMMENT '카드 사용 시간',
    `CARD_USE_PURPOSE`        VARCHAR(4000)    NULL        COMMENT '카드 사용 목적',
    `CARD_USE_PERSONNEL`      VARCHAR(1000)    NULL        COMMENT '카드 사용 인원',
    `CARD_USE_AMOUNT`         INT              NULL        COMMENT '카드 사용 금액',
    `CARD_USE_METHOD`         VARCHAR(100)     NULL        COMMENT '카드 사용 방법',
    `CARD_USE_REMARK`         VARCHAR(100)     NULL        COMMENT '카드 사용 비고',
    `CARD_USE_DELKEY`         VARCHAR(1000)    NULL        COMMENT '카드 사용 삭제키',
    `REGIST_DATE`             DATETIME         NULL        COMMENT '생성 일시',
    `MODIFY_DATE`             DATETIME         NULL        COMMENT '수정 일시',
    PRIMARY KEY (CARD_USE_ID)
);

-- 테이블 Comment 설정 SQL - CHAM.CARD_USE
ALTER TABLE CHAM.CARD_USE COMMENT '카드_사용';

-- Foreign Key 설정 SQL - CHAM.CARD_USE(CARD_OWNER_POSITION_ID) -> CHAM.CARD_OWNER_POSITION(CARD_OWNER_POSITION_ID)
ALTER TABLE CHAM.CARD_USE
    ADD CONSTRAINT FK_CARD_USE_CARD_OWNER_POSITION_ID_CARD_OWNER_POSITION_CARD_OWNE FOREIGN KEY (CARD_OWNER_POSITION_ID)
        REFERENCES CHAM.CARD_OWNER_POSITION (CARD_OWNER_POSITION_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - CHAM.CARD_USE(CARD_OWNER_POSITION_ID)
-- ALTER TABLE CHAM.CARD_USE
-- DROP FOREIGN KEY FK_CARD_USE_CARD_OWNER_POSITION_ID_CARD_OWNER_POSITION_CARD_OWNE;

-- Foreign Key 설정 SQL - CHAM.CARD_USE(CARD_USE_ADDR_ID) -> CHAM.CARD_USE_ADDR(CARD_USE_ADDR_ID)
ALTER TABLE CHAM.CARD_USE
    ADD CONSTRAINT FK_CARD_USE_CARD_USE_ADDR_ID_CARD_USE_ADDR_CARD_USE_ADDR_ID FOREIGN KEY (CARD_USE_ADDR_ID)
        REFERENCES CHAM.CARD_USE_ADDR (CARD_USE_ADDR_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - CHAM.CARD_USE(CARD_USE_ADDR_ID)
-- ALTER TABLE CHAM.CARD_USE
-- DROP FOREIGN KEY FK_CARD_USE_CARD_USE_ADDR_ID_CARD_USE_ADDR_CARD_USE_ADDR_ID;


-- REPLY Table Create SQL
-- 테이블 생성 SQL - CHAM.REPLY
CREATE TABLE CHAM.REPLY
(
    `REPLY_ID`     BIGINT           NOT NULL    AUTO_INCREMENT COMMENT '댓글 ID',
    `MEMBER_ID`    BIGINT           NOT NULL    COMMENT '회원 ID',
    `CARD_USE_ID`  BIGINT           NULL        COMMENT '카드 사용 ID',
    `REPLY_CONT`   VARCHAR(4000)    NULL        COMMENT '댓글 내용',
    `REGIST_DATE`  DATETIME         NULL        COMMENT '생성 일시',
    `MODIFY_DATE`  DATETIME         NULL        COMMENT '수정 일시',
    PRIMARY KEY (REPLY_ID)
);

-- 테이블 Comment 설정 SQL - CHAM.REPLY
ALTER TABLE CHAM.REPLY COMMENT '댓글';

-- Foreign Key 설정 SQL - CHAM.REPLY(MEMBER_ID) -> CHAM.MEMBER(MEMBER_ID)
ALTER TABLE CHAM.REPLY
    ADD CONSTRAINT FK_REPLY_MEMBER_ID_MEMBER_MEMBER_ID FOREIGN KEY (MEMBER_ID)
        REFERENCES CHAM.MEMBER (MEMBER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - CHAM.REPLY(MEMBER_ID)
-- ALTER TABLE CHAM.REPLY
-- DROP FOREIGN KEY FK_REPLY_MEMBER_ID_MEMBER_MEMBER_ID;

-- Foreign Key 설정 SQL - CHAM.REPLY(CARD_USE_ID) -> CHAM.CARD_USE(CARD_USE_ID)
ALTER TABLE CHAM.REPLY
    ADD CONSTRAINT FK_REPLY_CARD_USE_ID_CARD_USE_CARD_USE_ID FOREIGN KEY (CARD_USE_ID)
        REFERENCES CHAM.CARD_USE (CARD_USE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - CHAM.REPLY(CARD_USE_ID)
-- ALTER TABLE CHAM.REPLY
-- DROP FOREIGN KEY FK_REPLY_CARD_USE_ID_CARD_USE_CARD_USE_ID;