-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- CHAM_MONIMAP_MEMBER Table Create SQL
-- 테이블 생성 SQL - CHAM.CHAM_MONIMAP_MEMBER
CREATE TABLE CHAM.CHAM_MONIMAP_MEMBER
(
    `CHAM_MONIMAP_MEMBER_ID`           BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '자치연대 예산감시 회원 ID',
    `CHAM_MONIMAP_MEMBER_EMAIL`        VARCHAR(100)    NULL        COMMENT '자치연대 예산감시 회원 이메일',
    `CHAM_MONIMAP_MEMBER_NAME`         VARCHAR(100)    NULL        COMMENT '자치연대 예산감시 회원 이름',
    `CHAM_MONIMAP_MEMBER_SOCIAL_TYPE`  VARCHAR(50)     NULL        COMMENT '자치연대 예산감시 회원 소셜 타입',
    `CHAM_MONIMAP_MEMBER_SUB_ID`       VARCHAR(100)    NULL        COMMENT '자치연대 예산감시 회원 SUB ID',
    `CHAM_MONIMAP_MEMBER_ROLE`         VARCHAR(100)    NULL        COMMENT '자치연대 예산감시 회원 권한',
    `CHAM_MONIMAP_MEMBER_IMAGE_URL`    VARCHAR(500)    NULL        COMMENT '자치연대 예산감시 회원 이미지 URL',
    `REGIST_DATE`                      DATETIME        NULL        COMMENT '생성 일시',
    `MODIFY_DATE`                      DATETIME        NULL        COMMENT '수정 일시',
    PRIMARY KEY (CHAM_MONIMAP_MEMBER_ID)
);

-- 테이블 Comment 설정 SQL - CHAM.CHAM_MONIMAP_MEMBER
ALTER TABLE CHAM.CHAM_MONIMAP_MEMBER COMMENT '자치연대_예산감시_회원';


-- CHAM_MONIMAP_CARD_USE_ADDR Table Create SQL
-- 테이블 생성 SQL - CHAM.CHAM_MONIMAP_CARD_USE_ADDR
CREATE TABLE CHAM.CHAM_MONIMAP_CARD_USE_ADDR
(
    `CHAM_MONIMAP_CARD_USE_ADDR_ID`      BIGINT           NOT NULL    AUTO_INCREMENT COMMENT '자치연대 예산감시 카드 사용 장소 ID',
    `CHAM_MONIMAP_CARD_USE_ADDR_NAME`    VARCHAR(1000)    NULL        COMMENT '자치연대 예산감시 카드 사용 장소 이름',
    `CHAM_MONIMAP_CARD_USE_DETAIL_ADDR`  VARCHAR(4000)    NULL        COMMENT '자치연대 예산감시 카드 사용 상세 장소',
    `CHAM_MONIMAP_CARD_USE_IMAGE_URL`    VARCHAR(1000)    NULL        COMMENT '자치연대 예산감시 카드 사용 이미지 URL',
    `REGIST_DATE`                        DATETIME         NULL        COMMENT '생성 일시',
    `MODIFY_DATE`                        DATETIME         NULL        COMMENT '수정 일시',
    PRIMARY KEY (CHAM_MONIMAP_CARD_USE_ADDR_ID)
);

-- 테이블 Comment 설정 SQL - CHAM.CHAM_MONIMAP_CARD_USE_ADDR
ALTER TABLE CHAM.CHAM_MONIMAP_CARD_USE_ADDR COMMENT '자치연대_예산감시_카드_사용_장소';


-- CHAM_MONIMAP_CARD_OWNER_POSITION Table Create SQL
-- 테이블 생성 SQL - CHAM.CHAM_MONIMAP_CARD_OWNER_POSITION
CREATE TABLE CHAM.CHAM_MONIMAP_CARD_OWNER_POSITION
(
    `CHAM_MONIMAP_CARD_OWNER_POSITION_ID`    BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '자치연대 예산감시 카드 승인자 직위 ID',
    `CHAM_MONIMAP_CARD_OWNER_POSITION_NAME`  VARCHAR(100)    NULL        COMMENT '자치연대 예산감시 카드 승인자 직위 이름',
    `REGIST_DATE`                            DATETIME        NULL        COMMENT '생성 일시',
    `MODIFY_DATE`                            DATETIME        NULL        COMMENT '수정 일시',
    PRIMARY KEY (CHAM_MONIMAP_CARD_OWNER_POSITION_ID)
);

-- 테이블 Comment 설정 SQL - CHAM.CHAM_MONIMAP_CARD_OWNER_POSITION
ALTER TABLE CHAM.CHAM_MONIMAP_CARD_OWNER_POSITION COMMENT '자치연대_예산감시_카드_승인자_직위';


-- CHAM_MONIMAP_REPLY Table Create SQL
-- 테이블 생성 SQL - CHAM.CHAM_MONIMAP_REPLY
CREATE TABLE CHAM.CHAM_MONIMAP_REPLY
(
    `CHAM_MONIMAP_REPLY_ID`          BIGINT           NOT NULL    AUTO_INCREMENT COMMENT '자치연대 예산감시 댓글 ID',
    `CHAM_MONIMAP_MEMBER_ID`         BIGINT           NOT NULL    COMMENT '자치연대 예산감시 회원 ID',
    `CHAM_MONIMAP_CARD_USE_ADDR_ID`  BIGINT           NULL        COMMENT '자치연대 예산감시 카드 사용 장소 ID',
    `CHAM_MONIMAP_REPLY_CONT`        VARCHAR(4000)    NULL        COMMENT '자치연대 예산감시 댓글 내용',
    `REGIST_DATE`                    DATETIME         NULL        COMMENT '생성 일시',
    `MODIFY_DATE`                    DATETIME         NULL        COMMENT '수정 일시',
    PRIMARY KEY (CHAM_MONIMAP_REPLY_ID)
);

-- 테이블 Comment 설정 SQL - CHAM.CHAM_MONIMAP_REPLY
ALTER TABLE CHAM.CHAM_MONIMAP_REPLY COMMENT '자치연대_예산감시_댓글';

-- Foreign Key 설정 SQL - CHAM.CHAM_MONIMAP_REPLY(CHAM_MONIMAP_MEMBER_ID) -> CHAM.CHAM_MONIMAP_MEMBER(CHAM_MONIMAP_MEMBER_ID)
ALTER TABLE CHAM.CHAM_MONIMAP_REPLY
    ADD CONSTRAINT FK_CHAM_MONIMAP_REPLY_CHAM_MONIMAP_MEMBER_ID_CHAM_MONIMAP_MEMBER FOREIGN KEY (CHAM_MONIMAP_MEMBER_ID)
        REFERENCES CHAM.CHAM_MONIMAP_MEMBER (CHAM_MONIMAP_MEMBER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - CHAM.CHAM_MONIMAP_REPLY(CHAM_MONIMAP_MEMBER_ID)
-- ALTER TABLE CHAM.CHAM_MONIMAP_REPLY
-- DROP FOREIGN KEY FK_CHAM_MONIMAP_REPLY_CHAM_MONIMAP_MEMBER_ID_CHAM_MONIMAP_MEMBER;

-- Foreign Key 설정 SQL - CHAM.CHAM_MONIMAP_REPLY(CHAM_MONIMAP_CARD_USE_ADDR_ID) -> CHAM.CHAM_MONIMAP_CARD_USE_ADDR(CHAM_MONIMAP_CARD_USE_ADDR_ID)
ALTER TABLE CHAM.CHAM_MONIMAP_REPLY
    ADD CONSTRAINT FK_CHAM_MONIMAP_REPLY_CHAM_MONIMAP_CARD_USE_ADDR_ID_CHAM_MONIMAP FOREIGN KEY (CHAM_MONIMAP_CARD_USE_ADDR_ID)
        REFERENCES CHAM.CHAM_MONIMAP_CARD_USE_ADDR (CHAM_MONIMAP_CARD_USE_ADDR_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - CHAM.CHAM_MONIMAP_REPLY(CHAM_MONIMAP_CARD_USE_ADDR_ID)
-- ALTER TABLE CHAM.CHAM_MONIMAP_REPLY
-- DROP FOREIGN KEY FK_CHAM_MONIMAP_REPLY_CHAM_MONIMAP_CARD_USE_ADDR_ID_CHAM_MONIMAP;


-- CHAM_MONIMAP_CARD_USE Table Create SQL
-- 테이블 생성 SQL - CHAM.CHAM_MONIMAP_CARD_USE
CREATE TABLE CHAM.CHAM_MONIMAP_CARD_USE
(
    `CHAM_MONIMAP_CARD_USE_ID`             BIGINT           NOT NULL    AUTO_INCREMENT COMMENT '자치연대 예산감시 카드 사용 ID',
    `CHAM_MONIMAP_CARD_OWNER_POSITION_ID`  BIGINT           NULL        COMMENT '자치연대 예산감시 카드 승인자 직위 ID',
    `CHAM_MONIMAP_CARD_USE_ADDR_ID`        BIGINT           NULL        COMMENT '자치연대 예산감시 카드 사용 장소 ID',
    `CHAM_MONIMAP_CARD_USE_USER`           VARCHAR(500)     NULL        COMMENT '자치연대 예산감시 카드 사용 유저',
    `CHAM_MONIMAP_CARD_USE_REGION`         VARCHAR(4000)    NULL        COMMENT '자치연대 예산감시 카드 사용 지역',
    `CHAM_MONIMAP_CARD_USE_NAME`           VARCHAR(100)     NULL        COMMENT '자치연대 예산감시 카드 사용 이름',
    `CHAM_MONIMAP_CARD_USE_DATE`           DATE             NULL        COMMENT '자치연대 예산감시 카드 사용 일시',
    `CHAM_MONIMAP_CARD_USE_TIME`           TIME             NULL        COMMENT '자치연대 예산감시 카드 사용 시간',
    `CHAM_MONIMAP_CARD_USE_PURPOSE`        VARCHAR(4000)    NULL        COMMENT '자치연대 예산감시 카드 사용 목적',
    `CHAM_MONIMAP_CARD_USE_PERSONNEL`      VARCHAR(1000)    NULL        COMMENT '자치연대 예산감시 카드 사용 인원',
    `CHAM_MONIMAP_CARD_USE_AMOUNT`         INT              NULL        COMMENT '자치연대 예산감시 카드 사용 금액',
    `CHAM_MONIMAP_CARD_USE_METHOD`         VARCHAR(100)     NULL        COMMENT '자치연대 예산감시 카드 사용 방법',
    `CHAM_MONIMAP_CARD_USE_REMARK`         VARCHAR(100)     NULL        COMMENT '자치연대 예산감시 카드 사용 비고',
    `CHAM_MONIMAP_CARD_USE_DELKEY`         VARCHAR(1000)    NULL        COMMENT '자치연대 예산감시 카드 사용 삭제키',
    `REGIST_DATE`                          DATETIME         NULL        COMMENT '생성 일시',
    `MODIFY_DATE`                          DATETIME         NULL        COMMENT '수정 일시',
    PRIMARY KEY (CHAM_MONIMAP_CARD_USE_ID)
);

-- 테이블 Comment 설정 SQL - CHAM.CHAM_MONIMAP_CARD_USE
ALTER TABLE CHAM.CHAM_MONIMAP_CARD_USE COMMENT '자치연대_예산감시_카드_사용';

-- Foreign Key 설정 SQL - CHAM.CHAM_MONIMAP_CARD_USE(CHAM_MONIMAP_CARD_OWNER_POSITION_ID) -> CHAM.CHAM_MONIMAP_CARD_OWNER_POSITION(CHAM_MONIMAP_CARD_OWNER_POSITION_ID)
ALTER TABLE CHAM.CHAM_MONIMAP_CARD_USE
    ADD CONSTRAINT FK_CHAM_MONIMAP_CARD_USE_CHAM_MONIMAP_CARD_OWNER_POSITION_ID_CHA FOREIGN KEY (CHAM_MONIMAP_CARD_OWNER_POSITION_ID)
        REFERENCES CHAM.CHAM_MONIMAP_CARD_OWNER_POSITION (CHAM_MONIMAP_CARD_OWNER_POSITION_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - CHAM.CHAM_MONIMAP_CARD_USE(CHAM_MONIMAP_CARD_OWNER_POSITION_ID)
-- ALTER TABLE CHAM.CHAM_MONIMAP_CARD_USE
-- DROP FOREIGN KEY FK_CHAM_MONIMAP_CARD_USE_CHAM_MONIMAP_CARD_OWNER_POSITION_ID_CHA;

-- Foreign Key 설정 SQL - CHAM.CHAM_MONIMAP_CARD_USE(CHAM_MONIMAP_CARD_USE_ADDR_ID) -> CHAM.CHAM_MONIMAP_CARD_USE_ADDR(CHAM_MONIMAP_CARD_USE_ADDR_ID)
ALTER TABLE CHAM.CHAM_MONIMAP_CARD_USE
    ADD CONSTRAINT FK_CHAM_MONIMAP_CARD_USE_CHAM_MONIMAP_CARD_USE_ADDR_ID_CHAM_MONI FOREIGN KEY (CHAM_MONIMAP_CARD_USE_ADDR_ID)
        REFERENCES CHAM.CHAM_MONIMAP_CARD_USE_ADDR (CHAM_MONIMAP_CARD_USE_ADDR_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - CHAM.CHAM_MONIMAP_CARD_USE(CHAM_MONIMAP_CARD_USE_ADDR_ID)
-- ALTER TABLE CHAM.CHAM_MONIMAP_CARD_USE
-- DROP FOREIGN KEY FK_CHAM_MONIMAP_CARD_USE_CHAM_MONIMAP_CARD_USE_ADDR_ID_CHAM_MONI;


-- CHAM_MONIMAP_REPLY_IMAGE Table Create SQL
-- 테이블 생성 SQL - CHAM.CHAM_MONIMAP_REPLY_IMAGE
CREATE TABLE CHAM.CHAM_MONIMAP_REPLY_IMAGE
(
    `CHAM_MONIMAP_REPLY_IMAGE_ID`   BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '자치연대 예산감시 댓글 이미지 ID',
    `CHAM_MONIMAP_REPLY_ID`         BIGINT          NULL        COMMENT '자치연대 예산감시 댓글 ID',
    `CHAM_MONIMAP_REPLY_IMAGE_URL`  VARCHAR(500)    NULL        COMMENT '자치연대 예산감시 댓글 이미지 URL',
    `REGIST_DATE`                   DATETIME        NULL        COMMENT '생성 일시',
    `MODIFY_DATE`                   DATETIME        NULL        COMMENT '수정 일시',
    PRIMARY KEY (CHAM_MONIMAP_REPLY_IMAGE_ID)
);

-- 테이블 Comment 설정 SQL - CHAM.CHAM_MONIMAP_REPLY_IMAGE
ALTER TABLE CHAM.CHAM_MONIMAP_REPLY_IMAGE COMMENT '자치연대_예산감시_댓글_이미지';

-- Foreign Key 설정 SQL - CHAM.CHAM_MONIMAP_REPLY_IMAGE(CHAM_MONIMAP_REPLY_ID) -> CHAM.CHAM_MONIMAP_REPLY(CHAM_MONIMAP_REPLY_ID)
ALTER TABLE CHAM.CHAM_MONIMAP_REPLY_IMAGE
    ADD CONSTRAINT FK_CHAM_MONIMAP_REPLY_IMAGE_CHAM_MONIMAP_REPLY_ID_CHAM_MONIMAP_R FOREIGN KEY (CHAM_MONIMAP_REPLY_ID)
        REFERENCES CHAM.CHAM_MONIMAP_REPLY (CHAM_MONIMAP_REPLY_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - CHAM.CHAM_MONIMAP_REPLY_IMAGE(CHAM_MONIMAP_REPLY_ID)
-- ALTER TABLE CHAM.CHAM_MONIMAP_REPLY_IMAGE
-- DROP FOREIGN KEY FK_CHAM_MONIMAP_REPLY_IMAGE_CHAM_MONIMAP_REPLY_ID_CHAM_MONIMAP_R;