spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url:  jdbc:log4jdbc:mysql://${DB_URL}:${DB_PORT}/CHAM
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_BUCKET}

naver:
  redirecturi: http://localhost:5173/oauth/naver/callback
  clientId: 91cWDibxUKEhVvewsjk7
  client-secret: ${NAVER_CLIENT_SECRET}

google:
  redirecturi: http://localhost:5173/oauth/google/callback
  clientId: 943672896591-24nhnn9ni5hm3774866agm9nath60hhv.apps.googleusercontent.com
  client-secret: ${GOOGLE_CLIENT_SECRET}

kakao:
  redirecturi: http://localhost:5173/oauth/kakao/callback
  clientId: ff0c6740d1fc373d03b97e072f7efbb2
  client-secret: ${CLIENT_SECRET}

logging:
  file:
    name: /app/logs/cham.log
    level:
      root: INFO
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log

cookie:
  secure: false